name: postgres-service

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    hostname: postgres-db
    restart: always
    env_file:
      - path: ./.env
        required: true
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    # volumes:
    #   # - postgres_data:/var/lib/postgresql/data
    #   - ./DB/samples/dvdrental.tar:/docker-entrypoint-initdb.d/dvdrental.tar
    #   - ./DB/samples/restore-dvdrental.sh:/docker-entrypoint-initdb.d/restore-dvdrental.sh
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}", "-d", "${DB_NAME}"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - path: ./.env
        required: true
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    volumes:
      - ./outs/pgadmin:/var/lib/pgadmin
    #  - ./DB/samples/servers.json:/pgadmin4/servers.json
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
# volumes:
#   postgres_data:
